### ISSUE TITLE
Implement basic i18n support

### ISSUE THREAD

**Issue by boybundit** [boybundit/bootcamp-api#5]
The current plan is to support 2 locale: en, th

**Comment by noppadol78** [comment]
Convert SQL String from
   select ID,StationName[_lang], Test1, Caption[_lang] from ServiceStation;
to
   select ID,StationName_en StationName, Test1, Caption_en Caption from ServiceStation;

=== How to use ===
var sqlHelper = require('../lib/sql-helper.js');

sql = sqlHelper.conv_i18n('select ID,StationName[_lang], Test1, Caption[_lang] from ServiceStation;','en');
